irods_capability_automated_ingest/utils.py
There was a call to logger.log in the logging of a retry attempt which was causing errors on retry. It was using the 'failed' key which does not exist in the dict for structlog.
=> Fix call to logger.log

irods_capability_automated_ingest/sync_irods.py
Adds data size and modify keywords to the register_file operation to properly apply metadata from the filesystem without needing the extra call to dataObjModMeta after registering.
---
Note: This requires changes in iRODS server to be effective (see irods/irods#4066).
=> Add data size and modify KWs to register file

irods_capability_automated_ingest/flask_app.py, irods_capability_automated_ingest/irods_sync.py, irods_capability_automated_ingest/sync_irods.py, irods_capability_automated_ingest/sync_task.py, setup.py
Adds following command line options to allow for scanning S3 buckets:
- s3_endpoint_domain
- s3_region_name
- s3_keypair
- s3_proxy_url
s3_keypair must point to a file on the local machine with an S3 keypair.
s3_proxy_url is only needed if using a proxy to connect to the S3 endpoint.
S3 buckets are scanned via "chunking" of the retrieved objects such that each task is delegated a chunk of objects, rather than just one. The number of objects to process can be configured with the files_per_task option.
scandir is now the only option for scanning filesystems. As such, list_dir and scan_dir_list command line options have been removed.
Logic for grouping objects to process per task in S3 is now used for filesystem scanner as well. This allows for a significant performance boost to avoid …
=> Add S3 support

irods_capability_automated_ingest/sync_task.py
Added a check for is_symlink() in the check for is_dir() in sync_path.
=> [#69] Don't follow symlinks to dirs

setup.py
In the future, we should make sure 3.0.x is working and just tie to that version.
=> [#76] Pin redis version to 2.10.6

README.md, irods_capability_automated_ingest/sync_irods.py, irods_capability_automated_ingest/sync_task.py, irods_capability_automated_ingest/test/test_irods_sync.py
Now raise an exception when the target collection contains an invalid zone name.
Tests pass.
---
It would be nice to be able to catch this in the task manager before putting it on the queue but that would require an iRODS connection on the machine which kicks off the sync job.
=> [#31] Handle invalid zone name in target coll

setup.py
Also limits billiard version due to interdependencies
Test suite passes at the bench. Versions can be upgraded in a controlled manner from here\
=> [#88] Limit Celery version

irods_capability_automated_ingest/irods_sync.py
These are now hard-coded to 'restart', 'path', and 'file'.
=> [#107] Remove queue name options for irods_sync

irods_capability_automated_ingest/irods_sync.py
--redis_host, --redis_port, and --redis_db can be passed with the
command to override the CELERY_BROKER_URL settings.
=> [#90] Honor CELERY_BROKER_URL when present

irods_capability_automated_ingest/sync_irods.py
Zone hint and root collection cannot be seen by rodsusers, so running
ingest as any user other than a rodsadmin currently does not work. The
checks have been removed for now. This is a partial revert of SHA:
ecf5d1e95b9ae41de31c1a6ecd9ecb0bd36b0e3d
Also add NetworkException to sync_irods.
=> [#114] Remove zone hint check

README.md, docker/Dockerfile, docker/Dockerfile.ingest_worker, docker/README.md, docker/build_images.sh, docker/icommands.env, docker/irods_environment.json, docker/launch_worker.sh, docker/list_jobs.sh, docker/point_and_click.sh, docker/start_job.sh, docker/stop_job.sh
Provides two Dockerfiles:
1. Automated ingest as a python application image
2. Celery worker image based on ingest image
icommands.env and irods_envirionment.json files are required in and
outside of the container to make it run properly. This serves as the
connection info/authentication for our iRODS client.
Also provides a set of wrapper bash scripts for easy use of the
containers:
1. Scripts for listing, starting, stopping, and watching ingest jobs.
2. "Point-and-click" script: Minimizes typing by standing up Celery
workers, scanning the target to the destination logical path using
mainly default settings, and tearing everything down at the end.
NOTE: All of these scripts - especially point_and_click.sh - make a
series of assumptions about where they are running and what is
available …
=> [#109] Update docker steps for Celery

README.md, docker/build_images.sh, docker/ingest-test/Dockerfile.test, docker/ingest-test/README.md, docker/ingest-test/icommands.env, docker/ingest-test/irods_environment.json, docker/ingest-test/run_tests.sh, docker/launch_worker.sh, docker/s3_keypair, docker/start_job_s3.sh, irods_capability_automated_ingest/examples/no_retry.py, irods_capability_automated_ingest/examples/post_job.py, irods_capability_automated_ingest/examples/pre_job.py, irods_capability_automated_ingest/examples/retry.py, irods_capability_automated_ingest/irods_sync.py, irods_capability_automated_ingest/sync_irods.py, irods_capability_automated_ingest/sync_task.py, irods_capability_automated_ingest/test/test_irods_sync.py
This change cleans up the automated ingest test suite and ensures
that all tests are passing insofar as the server allows (Github issue
numbers referenced where relevant for skipping).
iRODS and redis server information is currently hard-coded for
the tests. iRODS client information is also hard-coded.
When fixing the UnicodeEncodeError tests, it appears that it is able
to create a collection in iRODS with a contained data object with no
name, leading to a data object to which one cannot refer. It must be
removed directly from the database. There is an issue in the main repo
for this: https://github.com/irods/irods/issues/4494
=> [#86][#117] Test suite cleanup + docker image

irods_capability_automated_ingest/sync_task.py
Apparently the Minio client was instantiated without the S3 region parameter. I added it to the the list of input parameters.
=> fixed the parsing of the S3 region parameter

irods_capability_automated_ingest/sync_irods.py
`$IRODS_ENVIRONMENT_FILE` is still supported but if the env contains the
supported environment variables, this makes deployment of worker nodes
much easier. Here are the supported/expected environment variables:
```
IRODS_HOST
IRODS_PORT
IRODS_USER_NAME
IRODS_ZONE_NAME
IRODS_PASSWORD
```
If any of these is missing, an environment file in JSON format is
expected to be at the path specified by `$IRODS_ENVIRONMENT_FILE`. The
environment file should contain at least the following information:
```
{
"irods_host": <string>,
"irods_port": <int>,
"irods_user": <string>,
"irods_zone_name": <string>
}
```
An `.irodsA` file is expected to be in the home directory of the Linux
user running the Celery workers on a given node in order to authenticate
with iRODS.
=> [#147][#157] Allow running workers with env only

docker/performance_testing/Dockerfile.ingest_worker, docker/performance_testing/README.md, docker/performance_testing/docker-compose.yml
This change adds a Docker Compose project which sets up an environment
for testing performance of the ingest tool in various conditions. The
following variables can be adjusted:
- number of files ingested (as well as subdirectory depth)
- traffic control delay
- number of workers (nodes x --concurrency?)
=> [#159] add performance benchmark test harness

irods_capability_automated_ingest/sync_actions.py
Variable failures equals None when a job have successfully executed
---
Identical to https://github.com/irods/irods_capability_automated_ingest/pull/178
=> [#177] Fix wrong exit code with --synchronous option

irods_capability_automated_ingest/scanner.py, irods_capability_automated_ingest/test/test_irods_sync.py
Due to the recent refactor and lack of test coverage in this area, `--exclude_file_name` has been broken since 0.4.0. This is because the implementation moved control blocks but was not updated properly to adapt to its new context. This fix is not a complete solution, but allows the option to be used as expected once again.
=> Fix exclude_file_name being ignored

docker/ingest-test/test/Dockerfile, irods_capability_automated_ingest/test/test_irods_sync.py, setup.py
- log Python 3.11 compatibility
- apply `CELERY_BROKER_URL` environment variable change for all tests
=> changes for next release (v0.4.2)

irods_capability_automated_ingest/irods_sync.py, irods_capability_automated_ingest/scanner.py, irods_capability_automated_ingest/sync_actions.py, irods_capability_automated_ingest/sync_irods.py
This fixes the "File not found error" that occurs when trying to run a PUT or PUT_SYNC for files from an S3 resource. I am using Minio to get the file from the S3 bucket. Currently can not use parallelization to do the put for S3 objects, which will need to be worked on. Not sure what to do with that at this point.  I have also included checksum comparison with the Etag for both normal files in an S3 bucket and also multipart upload files. I am not sure if this is the correct way to do the checksum, so feedback there would be good. The default chunk size for multipart uploads to Amazon S3 is 8 MB, but I have read online that it may not always be the same, so I have added a command line argument to the ingest job to specify a different chunk size.
=> [#129] single stream put from S3

irods_capability_automated_ingest/examples/metadata.py
Addresses #212. Just changed operation type.
=> changed ```REGISTER``` to ```REGISTER_SYNC``` in example event handlers for metadata.py. 

irods_capability_automated_ingest/examples/append_json.py, irods_capability_automated_ingest/examples/coll_create_pre_and_post.py, irods_capability_automated_ingest/examples/coll_modify_pre_and_post.py, irods_capability_automated_ingest/examples/data_obj_create_pre_and_post.py, irods_capability_automated_ingest/examples/data_obj_modify_pre_and_post.py, irods_capability_automated_ingest/examples/no_retry.py, irods_capability_automated_ingest/examples/register_with_peps.py, irods_capability_automated_ingest/examples/retry.py, irods_capability_automated_ingest/examples/timeout.py, irods_capability_automated_ingest/scanner.py, irods_capability_automated_ingest/sync_irods.py, irods_capability_automated_ingest/sync_task.py, irods_capability_automated_ingest/test/test_irods_sync.py
Addresses #219 (for real)
This partially reverts the work done in https://github.com/irods/irods_capability_automated_ingest/pull/236.
This change primarily adds tests for almost all relevant operations for all pre/post event handler methods that we currently support. This is meant to act as a minimal baseline to ensure that the pre/post methods are executing properly.
Case in point: Possible bug was discovered while writing these tests and has been created here: #240.
All new tests pass. Running full suite now.
=> Add *args to all example event handler methods, and add tests for pre/post event handler methods

README.md, docker/demo/compose.yaml, irods_capability_automated_ingest/irods/filesystem.py, irods_capability_automated_ingest/irods/s3_bucket.py
Addresses #289
The node name thing is to prevent a warning message that appears if multiple Celery worker nodes are running in the same host.
=> Fix PUT operation documentation and give node name to demo Celery workers

docker/demo/compose.yaml, docker/ingest-test/docker-compose.yml, docker/ingest-test/icommands.env, irods_capability_automated_ingest/irods/irods_utils.py, irods_capability_automated_ingest/irods/s3_bucket.py, irods_capability_automated_ingest/tasks/s3_bucket_tasks.py, irods_capability_automated_ingest/test/test_delete_modes.py, irods_capability_automated_ingest/test/test_irods_sync.py, irods_capability_automated_ingest/test/test_lib.py, irods_capability_automated_ingest/test/test_s3_bucket_scan.py
Addresses #124 
Addresses #132 
Addresses #285
All tests are passing. I thought this was going to be an S3 bug fixing PR until I discovered that #124 is not exclusive to S3.
The new S3 test suite was loosely based on the `test_delete_modes` structure for doing things.
Also added a testing library to reduce some duplicate code.
=> Add very basic S3 tests and fix some S3 bugs

README.md, irods_capability_automated_ingest/redis_key.py, irods_capability_automated_ingest/sync_actions.py, irods_capability_automated_ingest/sync_job.py, irods_capability_automated_ingest/sync_logging.py, irods_capability_automated_ingest/tasks/filesystem_tasks.py, irods_capability_automated_ingest/tasks/s3_bucket_tasks.py, irods_capability_automated_ingest/test/test_irods_sync.py
Addresses #91 
Addresses #92 
Addresses #93 
Addresses #210 
Addresses #293
I'm contemplating adding tests for these subcommands, but it seems a little tricky (hence, draft PR) and there are no existing tests for any of the subcommands other than `start`. Existing tests are passing.
Also, the two commits referencing #210 (only) can be squashed into one if we like the solution of maintaining a list of stopped jobs. Otherwise, we can drop the second commit because the first one addresses the issue (albeit, not as well, IMO).
=> `irods_sync` script fixes and enhancements (plus one other bug fix)

setup.py
Addresses #266
This is required in order for ingest to work with python 3.12. Additionally, this removes the specific versioning requirements around the `billiard` package. This is a dependency of Celery, so we can just let `pip` figure out what version to install.
I have confirmed that tests are passing on python 3.8, 3.12, and 3.13 with this change.
=> [#266] Bump Celery minimum version
